FROM ubuntu:latest

FROM gradle:8.8-jdk17 AS builder

WORKDIR /opt/project
COPY notification_service/build/libs/postman_notification.jar ./
#RUN gradle clean build --no-daemon


FROM openjdk:17-jdk-slim
EXPOSE 8081
COPY --from=builder /opt/project/postman_notification.jar /opt/project/build/libs/postman_notification.jar
CMD ["java", "-jar", "/opt/project/build/libs/postman_notification.jar"]
