FROM ubuntu:latest

FROM gradle:8.8-jdk17 AS builder

WORKDIR /opt/project
COPY auth_service/build/libs/postman-auth.jar ./
#RUN gradle clean build --no-daemon


FROM openjdk:17-jdk-slim
EXPOSE 8080
COPY --from=builder /opt/project/postman-auth.jar /opt/project/build/libs/postman-auth.jar
CMD ["java", "-jar", "/opt/project/build/libs/postman-auth.jar"]
