FROM ubuntu:latest

FROM gradle:8.8-jdk17 AS builder

WORKDIR /opt/project
COPY worker/build/libs/worker.jar ./
#RUN gradle clean build --no-daemon


FROM openjdk:17-jdk-slim
EXPOSE 8082
COPY --from=builder /opt/project/worker.jar /opt/project/build/libs/worker.jar
CMD ["java", "-jar", "/opt/project/build/libs/worker.jar"]
